```yaml id="vx9c98"
---
- hosts: localhost
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: /var/snap/jenkins/5022/workspace/MavenAnsible/target/MavenAnsibleWebApp1.war
        dest: /opt/tomcat/webapps/MavenAnsibleWebApp1.war

    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted
```
